name: Coverage

on: [push]

env:
  COVERAGE_VARS: "llvm-cov.env"
  NEXTEST_ARCHIVE: "nextest.tar.zst"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:1.71-slim
      env:
        RUST_BACKTRACE: full
        DEBIAN_FRONTEND: noninteractive
        CARGO_TERM_COLOR: always
        CARGO_LLVM_COV_SETUP: "no"
    steps:
      # General build dependencies. Libssl-dev is required to build
      # cargo-nextest.
      - name: Update and install build dependencies
        run: |
          apt-get update
          apt-get -y install libssl-dev pkg-config
      - name: Install LLVM tools
        run: rustup component add llvm-tools-preview
      - name: Install Rust tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov,cargo-nextest
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build instrumented test binaries and archive them
        shell: bash
        run: |
          # Test coverage
          cargo llvm-cov show-env --export-prefix | tee "$COVERAGE_VARS"
          source "$COVERAGE_VARS"
          # Build everything to make sure nothing breaks
          cargo build --workspace --all-targets
          # Run Nextest
          cargo nextest run --workspace --all-targets
          cargo llvm-cov report
